require "rake/testtask"

Rake::TestTask.new do |t|
  t.test_files = FileList['*_test.rb']
end
desc "Run tests"

Rake::TestTask.new(:bench) do |t|
  t.pattern = '*_benchmark.rb'
end
desc "Run benchmarks"

task default: :test
